### ISSUE TITLE
Could not find a declaration file for module '@react-navigation/native'.

### ISSUE THREAD

**Issue by Zajjaj-Khan** [react-navigation/react-navigation#12534]
### Current behavior

'NavigationContainer' is declared but its value is never read.ts(6133)
Could not find a declaratio

![Image](https://github.com/user-attachments/assets/1bde5646-b4c9-4934-ad6c-ae859996825e)

![Image](https://github.com/user-attachments/assets/6ff9f6bf-9232-44fe-b6e1-6a5c6fc25dba)

n file for module '@react-navigation/native'. '/home/zajjaj/Documents/Valient/node_modules/@react-navigation/native/lib/module/index.js' implicitly has an 'any' type.
  There are types at '/home/zajjaj/Documents/Valient/node_modules/@react-navigation/native/lib/typescript/src/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.ts(7016)

![Image](https://github.com/user-attachments/assets/c3e61e6b-23de-4f0f-82be-d8d010cefeed)

### Expected behavior

There shouldnt be any types error.

### Reproduction

-

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-drawer-layout             |
| react-native-tab-view                  |
| react-native-screens                   |
| react-native-safe-area-context         |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by satya164** [comment]
As the error says, you need to update your `moduleResolution` field to `bundler` in `tsconfig.json`.

**Comment by devalirzayev** [comment]
@satya164 that's not correct solution as expo does not allow bundler to be set in tsconfig.json.

**Comment by devalirzayev** [comment]
This issue should be reopened.

**Comment by satya164** [comment]
@devalirzayev Expo works fine with `moduleResolution: "bundler"`. This is the proper configuration to match Metro's behavior, which is React Native's bundler and this configuration is also mentioned in the official React Native blog post: https://reactnative.dev/blog/2023/06/21/package-exports-support#enabling-package-exports-beta

Expo Router doesn't work with it, which is an issue with Expo Router and you should track it there https://github.com/expo/expo/issues/32850

**Comment by ntucker** [comment]
Do people not use jest? It still requires commonjs to run.

**Comment by satya164** [comment]
@ntucker you just need to transform `@react-navigation` for Jest in your config:

```js
{
  "preset": "react-native",
  "transformIgnorePatterns": [
    "node_modules/(?!(@react-native|react-native|@react-navigation)/)"
  ]
}
```

**Comment by ntucker** [comment]
> [@ntucker](https://github.com/ntucker) you just need to transform `@react-navigation` for Jest in your config:
> 
> {
>   "preset": "react-native",
>   "transformIgnorePatterns": [
>     "node_modules/(?!(@react-native|react-native|@react-navigation)/)"
>   ]
> }

Doesn't work

```bash
FAIL ReactNative packages/react/src/hooks/__tests__/useSuspense.native.tsx
  ● Test suite failed to run

    Must use import to load ES Module: /home/********/project/node_modules/@react-navigation/native/lib/module/index.js

      12 | import { jest } from '@jest/globals';
      13 | import { Temporal } from '@js-temporal/polyfill';
    > 14 | import { NavigationContainer } from '@react-navigation/native';
         | ^
      15 | import { createNativeStackNavigator } from '@react-navigation/native-stack';
      16 | import { render, act, screen } from '@testing-library/react-native';
      17 | import {

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:850:21)
      at Object.require (packages/react/src/hooks/__tests__/useSuspense.native.tsx:14:1)
```

from https://github.com/reactive/data-client/pull/3458

Jest config line like you said: https://github.com/reactive/data-client/blob/renovate/react-navigation-monorepo/jest.config.js#L94

**Comment by satya164** [comment]
> Jest config line like you said

@ntucker It's not the same as what I said since you have a very different jest setup. The above snippet is with `react-native` preset that uses `babel-jest`, and you can verify that it works in a fresh React Native app. This setup should also work fine with a fresh jest config with `bable-jest` as the transformer.

Your setup may need other adjustments. The error points to https://github.com/wclr/ts-node-dev/issues/314, but you'll have to do your research based on the tools you use.

**Comment by ntucker** [comment]
The jest config is copied from https://github.com/facebook/react-native/blob/main/packages/react-native/jest-preset.js directly; it cannot be used as such as it needs some overrides - for example adding react-navigation to the list. (you'll notice it's not included in the preset). ts-node is not used - babel-jest is. ts-node is only included because for some reason some package managers require you to list all optional peer deps, and jest has ts-node as a peer dep.

See the jest-config package entry in yarn.lock. jest-config is required by all jest packages like the cli:
```
"jest-config@npm:^29.7.0":
  version: 29.7.0
  resolution: "jest-config@npm:29.7.0"
  dependencies:
    "@babel/core": "npm:^7.11.6"
    "@jest/test-sequencer": "npm:^29.7.0"
    "@jest/types": "npm:^29.6.3"
    babel-jest: "npm:^29.7.0"
    chalk: "npm:^4.0.0"
    ci-info: "npm:^3.2.0"
    deepmerge: "npm:^4.2.2"
    glob: "npm:^7.1.3"
    graceful-fs: "npm:^4.2.9"
    jest-circus: "npm:^29.7.0"
    jest-environment-node: "npm:^29.7.0"
    jest-get-type: "npm:^29.6.3"
    jest-regex-util: "npm:^29.6.3"
    jest-resolve: "npm:^29.7.0"
    jest-runner: "npm:^29.7.0"
    jest-util: "npm:^29.7.0"
    jest-validate: "npm:^29.7.0"
    micromatch: "npm:^4.0.4"
    parse-json: "npm:^5.2.0"
    pretty-format: "npm:^29.7.0"
    slash: "npm:^3.0.0"
    strip-json-comments: "npm:^3.1.1"
  peerDependencies:
    "@types/node": "*"
    ts-node: ">=9.0.0"
  peerDependenciesMeta:
    "@types/node":
      optional: true
    ts-node:
      optional: true
  checksum: 10c0/bab23c2eda1fff06e0d104b00d6adfb1d1aabb7128441899c9bff2247bd26710b050a5364281ce8d52b46b499153bf7e3ee88b19831a8f3451f1477a0246a0f1
  languageName: node
  linkType: hard
```
